{
 "title": "Mikrotik Loki Logs",
 "description": "Mikrotik Loki Logs ",
 "tags": [
  "mikrotik",
  "loki"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "routerboard",
    "label": "Routerboard",
    "query": {}
   },
   {
    "name": "topics",
    "label": "Topics",
    "query": "account,caps,critical,error,firewall,info,warning,wireless"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" }
  ]
 },
 "panels": [
  {
   "title": "Log Counts By Topic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\", routerboard=\"$routerboard\"} [$__interval] |~\"(?i)$topics\" |~\"(?i)$searchable_pattern\")",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Log Counts By Topic Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"syslog\", routerboard=\"$routerboard\"} [$__interval] | pattern \"<prefix>:<_>\" |~\"(?i)$topics\" |~\"(?i)$searchable_pattern\")",
     "legendFormat": "{{prefix}}"
    }
   ]
  },
  {
   "title": "Logs Lines By Topic",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"syslog\", routerboard=\"$routerboard\"} |~\"(?i)$topics\" |~\"(?i)$searchable_pattern\""
    }
   ]
  }
 ]
}